#!/bin/sh

which brew >/dev/null 2>&1
if [ "$?" -ne 0 ]; then
    echo "Brew not found. Installing homebrew.";
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    exit 0;
fi
